services:
  db:
    image: mysql:8.0
    container_name: mysql_prestamos
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: prestamos_utp_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
